### ISSUE TITLE
add pull to refresh?

### ISSUE THREAD

**Issue by alahammad** [JimiSmith/PinnedHeaderListView#11]
Hello ,
First thanks for your library i loved it :+1: 
second i want to implement pull to refresh class to your library but sections and positions not correct..
can you help me with this issue 

thanks ..

**Comment by JimiSmith** [comment]
Which pull to refresh library are you using?

**Comment by alahammad** [comment]
I try all of library the same issue, do you recommended use specific one

**Comment by JimiSmith** [comment]
I've got it working with [Chris Banes' PullToRefresh library](https://github.com/chrisbanes/Android-PullToRefresh)

I've posted a Gist with the relevant code - https://gist.github.com/JimiSmith/5559394

Basically you'll need to modify his library to support PinnedHeaderListView(see PullToRefreshPinnedHeaderListView.java)

If you have any issues with this, please reopen the issue and provide a screenshot of the problem
