### ISSUE TITLE
Error when addHeaderview

### ISSUE THREAD

**Issue by windjp** [JimiSmith/PinnedHeaderListView#2]
hi JimiSmith,
     I'm using your PinnedHeaderListView class and it works well, but when I add a headerview it doesn't work what i want, the header view which I added is replaced by a blank section header view. below is my sectionadapter class code, and what should I do. thanks.

```
public View getItemView(int section, int position, View convertView, ViewGroup parent) {
    ItemViewHolder holder = null;
    if (convertView == null) {
        holder = new ItemViewHolder();
        convertView = (LinearLayout) this.mInflater.inflate(R.layout.view_add_friend_item, null);
        holder.headimg = (ImageView)convertView.findViewById(R.id.iv_addfriend_avater);
        holder.nickname = (TextView)convertView.findViewById(R.id.tv_addfriend_friend_name);
        holder.desc = (TextView)convertView.findViewById(R.id.tv_addfriend_friend_des);
        holder.addbtn = (Button)convertView.findViewById(R.id.bt_addfriend_add);

        convertView.setTag(holder);  
    } else {
        holder = (ItemViewHolder) convertView.getTag();
    }
    UserSection currentSection = sectionList.get(section);
    List<UserInfo> userList = currentSection.getUserList();
    UserInfo currentUser = userList.get(position);
    holder.nickname.setText(currentUser.getName());
    Utils.setPortrait(this.mContext, currentUser.getHeaderS(), holder.headimg);

    return convertView;
}

@Override
public View getSectionHeaderView(int section, View convertView, ViewGroup parent) {
    HeaderViewHolder holder = null;
    if (convertView == null) {
        holder = new HeaderViewHolder();
        LayoutInflater inflator = (LayoutInflater)parent.getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        convertView = (LinearLayout) inflator.inflate(R.layout.item_section_adapter_header, null);
        holder.title = (TextView)convertView.findViewById(R.id.tv_section_title);
        convertView.setTag(holder);

    } else {
        holder = (HeaderViewHolder) convertView.getTag();
    }
    UserSection currentSection = sectionList.get(section);
    holder.title.setText(currentSection.getSectionTitle());
    return convertView;
}
```

**Comment by JimiSmith** [comment]
Is it only blank when pinned?

If you use your layout file for the header in the example, does it show then?

If not, could you post the layout file.

**Comment by windjp** [comment]
hi,
   thanks for your rapidly reply.
   I tried the example codes, the answer is same. The header view will be replaced by a duplicated first section header(Section 0 header), remain the size of header view.
   and the other problem is , when scrolled,  some item will not display.
   maybe you can try adding a header view in your MainActivity and see what happen.
   I think something is wrong in PinnedHeaderListView, can you check this, thx.

**Comment by JimiSmith** [comment]
Could you upload a screenshot of the problem?

**Comment by windjp** [comment]
![ 20130106193924](https://f.cloud.github.com/assets/3194523/45895/da9a0126-57f5-11e2-9b19-9cf84cf9374d.png)

**Comment by JimiSmith** [comment]
I haven't been able to reproduce this issue on any of my devices. Could you please make sure you have the latest code, and if the issue still occurs, upload a sample project that demonstrates the problem.

Thanks

**Comment by windjp** [comment]
hi Jimi,
    I think something is wrong in 
           'public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount)' 
     method in PinnedHeaderListView class, because the first visible item is the added header, when we call addHeaderView, I try to firstVisibleItem=firstVisibleItem -1, and return -1 by default in getSectionForPosition method, seems got some progress.
    just my guess

**Comment by JimiSmith** [comment]
Sorry, I misunderstood your bug at first. I can now reproduce it so hopefully I'll be able to fix it during the course of tomorrow.

**Comment by windjp** [comment]
:) misunderstanding maybe because of my poor english, looking forward to your update 

thank you very much
