### ISSUE TITLE
why i can't add header for list view

### ISSUE THREAD

**Issue by alahammad** [JimiSmith/PinnedHeaderListView#4]
hi,
i can't add view for list view, like this :
mListView.addFooter(layout);
the error :
java.lang.ClassCastException: android.widget.HeaderViewListAdapter cannot be cast to za.co.immedia.pinnedheaderlistview.SectionedBaseAdapter

please check this and fix it

**Comment by JimiSmith** [comment]
Please could you post more code of how you are calling this method?

The adding of a footer view works - you can see this in the example

**Comment by alahammad** [comment]
here is my code :
        View layout = (LinearLayout) getLayoutInflater().inflate(
                R.layout.pay_btn, null, false);
        mPayNow = (Button) layout.findViewById(R.id.btn_pay_now);
        mPayNow.setOnClickListener(listner);
        mListView.addFooterView(layout);
but why error, i don't know :(

**Comment by JimiSmith** [comment]
Could you post the full stack trace with line numbers?

**Comment by alahammad** [comment]
03-07 15:08:53.048: E/AndroidRuntime(6519): FATAL EXCEPTION: main
03-07 15:08:53.048: E/AndroidRuntime(6519): java.lang.ClassCastException: android.widget.HeaderViewListAdapter cannot be cast to za.co.immedia.pinnedheaderlistview.SectionedBaseAdapter
03-07 15:08:53.048: E/AndroidRuntime(6519):     at za.co.immedia.pinnedheaderlistview.PinnedHeaderListView$OnItemClickListener.onItemClick(PinnedHeaderListView.java:142)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at android.widget.AdapterView.performItemClick(AdapterView.java:292)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at android.widget.AbsListView$PerformClick.run(AbsListView.java:2713)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at android.widget.AbsListView$1.run(AbsListView.java:3468)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at android.os.Handler.handleCallback(Handler.java:605)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at android.os.Handler.dispatchMessage(Handler.java:92)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at android.os.Looper.loop(Looper.java:137)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at android.app.ActivityThread.main(ActivityThread.java:4507)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at java.lang.reflect.Method.invokeNative(Native Method)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at java.lang.reflect.Method.invoke(Method.java:511)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
03-07 15:08:53.048: E/AndroidRuntime(6519):     at dalvik.system.NativeStart.main(Native Method)

**Comment by alahammad** [comment]
when comment my code works, but if add footer view crash i don't know why .

**Comment by JimiSmith** [comment]
I've pushed a commit that fixes this issue for me. Please test it out

**Comment by alahammad** [comment]
Awesome, thanks for your update
