### ISSUE TITLE
Making the library generic like ArrayAdapter<T>

### ISSUE THREAD

**Issue by yccheok** [JimiSmith/PinnedHeaderListView#9]
Hi Jimi Smith,

First of all, I really would like to thank you for creating such a great library. Although I had looked into several tutorials to do my own implementation, none of them meet my requirement. 

Till I found your libraries. It really saves me from few days of works. Once again, thank you so much! One thing I like about the library is that, it takes care of different convert views.

Making the library generic like ArrayAdapter<T> would be great. But so far, I can live without it :)

**Comment by JimiSmith** [comment]
This isn't something I'm looking at implementing in the near future. But if you want to implement it yourself, I'm happy to accept pull requests
